### ISSUE TITLE
Suggestion for calculator pages

### ISSUE THREAD

**Issue by ZEZAY** [PitchapaSaelim/Have-A-Night-Day#63]
After I check the Installation Instructions, it works very well, but when I try to use the app I found something to suggest as a user.

For the calculator pages (both calculator2 and 3) after clicking the submit button it immediately redirects to the home page too fast, so I couldn't see the result yet. My suggestion is you should try to hold the redirects for at least 5 seconds or maybe just pop up the result on the home page after the redirection.

**Comment by PitchapaSaelim** [comment]
Thank you for your suggestion.
