### ISSUE TITLE
Graph problem.

### ISSUE THREAD

**Issue by Firstyfirst** [PitchapaSaelim/Have-A-Night-Day#65]
The information graph in the profile page really hard to understand. I know only the name of the graph, but I do not understand the bar how related with sleep data. The x-axis and y-axis must have the name and unit of each x-axis. Another little problem is the picture of graph do not on the center of page.

**Comment by PitchapaSaelim** [comment]
Thank you for your suggestion. The graph can't be used right now, it's just a demo graph. I will fix it in the next iteration.
