### ISSUE TITLE
Suggestion and a Tiny Error

### ISSUE THREAD

**Issue by kaesrel** [PitchapaSaelim/Have-A-Night-Day#66]
On the navigation bar on the top right, the word "Calculator" is misspelled as "Caculator".

The time unit displayed in the home page is in a 12 hour clock (AM/PM), but the time displayed in the calculator page is in a 24 hour clock; which is a little inconsistent. It slightly confuses me at first. 

I suggest either using only one type of hour clock, or include both types for the user to select.

There is no error with the installation process. It is pretty easy to follow. 
Good luck with your work. :grin:

**Comment by PitchapaSaelim** [comment]
Thank you for your suggestion. Sorry for the tiny error, I will fix it in the next iteration.
