### ISSUE TITLE
Functionality: The site accept to create user with impossible birthday.

### ISSUE THREAD

**Issue by ZEZAY** [PitchapaSaelim/Have-A-Night-Day#70]
I try to create user who born in 3333 and 0001, and it works!

URL: https://haveanightday.herokuapp.com/registration/

![image](https://user-images.githubusercontent.com/44806732/100918507-28c76280-350b-11eb-8c96-9795cb0ba352.png)
![image](https://user-images.githubusercontent.com/44806732/100918526-2d8c1680-350b-11eb-9a10-a23882b03ea1.png)
![image](https://user-images.githubusercontent.com/44806732/100918538-32e96100-350b-11eb-89e1-a412c2d75568.png)

**Comment by PitchapaSaelim** [comment]
We fixed it, thank you.
