### ISSUE TITLE
After you create a new account site will redirect you to the account you previously log in to.

### ISSUE THREAD

**Issue by Sahadporn** [PitchapaSaelim/Have-A-Night-Day#71]
url: https://haveanightday.herokuapp.com/registration/

After you create a new account site will redirect you to the account you previously log in to.

How to reproduce the problem:
1. In the login page click Register here! and will pop up a new tab for registration.
2. After creating a new account login to that account in same tab as the tab you wrote the registration. 
3. Go back to the login page in the first tab and click Register here! again.
4. I think it suppose to pop up a new tab but instead it's use the same tab as the tab you have your previous account on.
5. Create a new account again. It will redirect you to your previous login account.

![image](https://user-images.githubusercontent.com/59825486/100917465-c883f100-3509-11eb-85f9-b5c744afe532.png)

**Comment by PitchapaSaelim** [comment]
Can you explain more details about this issue?

**Comment by Sahadporn** [comment]
I think the problem with this issue is that in the login page when you click the link to register it will pop up a new tab.

In 5. if you click the register link again instead of popping up a new tab it goes to the same tab as your previous pop up tab.
Even if you logged out after you go click the register link in the login page, register a new account and log in to your new account it will still direct you to your previous account that you logged out before.

But the last time I checked you have changed the register link from login page redirect to registration page within the same tab, right?

There is no more pop up tab, so I think that's also fixed the bug on this issue.
But still, thank you for reading my issue.
