### ISSUE TITLE
Many unnecessary packages in requirements.txt

### ISSUE THREAD

**Issue by jbrucker** [PitchapaSaelim/Have-A-Night-Day#74]
Have you looked at your own requirements.txt file?

It has **lots** of packages that I'm pretty sure you
don't need.  
It is important for developers to know the effect
of what they are doing -- don't just blindly write code.

Why so many packages?
Why freeze the version to be **exactly** some
value instead of **at least** some value?

Anyone or any cloud host that runs your app will 
need to install all the packages.

You should try deleting everyone from requirements.txt
except Django and the database driver, and delete
the virtualenv on your own machine.

Then create a new virtualenv, use your own instructions
to install packages and run it.
It will probably fail because you are missing 1 or 2 packages,
so add them to requirements,txt, use pip -r requirements.txt
to add them to the virtualenv and run it again.

Repeat this until it works.

**Comment by PitchapaSaelim** [comment]
Sorry for the mistake, we remove unnecessary packages in requirements.txt already. Thank you.
