### ISSUE TITLE
Calculator ValueError

### ISSUE THREAD

**Issue by kaesrel** [PitchapaSaelim/Have-A-Night-Day#75]
I removed the time of the time field for the calculator at the home page https://haveanightday.herokuapp.com/home/
![image](https://user-images.githubusercontent.com/59855413/100957311-c98a4200-354c-11eb-9670-cfb792534ee6.png)

I clicked the calculate button and then...

![image](https://user-images.githubusercontent.com/59855413/100957081-6ac4c880-354c-11eb-9d65-9fa0e4f5f8eb.png)

**Comment by PitchapaSaelim** [comment]
We fixed it, thank you.
