### ISSUE TITLE
DEBUG show when access to wrong URL format

### ISSUE THREAD

**Issue by bhatara007** [PitchapaSaelim/Have-A-Night-Day#76]
URL: https://haveanightday.herokuapp.com/sdfsdf
![image](https://user-images.githubusercontent.com/59830751/101073099-8b833180-35d1-11eb-8858-118706e8dcf9.png)
How to fixed:
change the DEBUG variable that equal to True in your Django settings file. Change that to False,

**Comment by PitchapaSaelim** [comment]
Thank you, I fixed it.
